# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensor/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensor/
Content-Type: application/json

{
  "name": "ESPххх",
  "description": "Датчик ххх"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensor/1/
Content-Type: application/json

{
  "description": "датчик 1 на кухне"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 5,
  "temperature": 36.6
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/3/
Content-Type: application/json
